import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/controllers/footers/foter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="bg-black my-5 py-5 md:pl-32 max-md:text-center">
          <Footer />
        </div>
      </body>
    </html>
  );
}
